version: '3.8'

services:
  hasura-sushi:
    image: hasura/graphql-engine:v2.34.0
    container_name: sushi-hasura
    ports:
      - '7008:8080'
    restart: unless-stopped
    env_file:
      - hasura/hasura-local.env
